# Stage 1
# Specify a base image
FROM node:13.12.0-alpine AS base
WORKDIR /app
# Install dependencies
COPY package.json .
COPY package-lock.json ./
RUN npm install 
COPY . .
# Default command
RUN npm run build

FROM node:13.12.0-alpine AS release
COPY --from=base /app /app
COPY package*.json ./
COPY package-lock.json ./
RUN npm install
COPY index.js .

EXPOSE 80
CMD ["npm", "run", "prod"]